import { MpvIpcClient } from './mpv-ipc-client';
import { MpvProcessManager, MpvOptions } from './mpv-process';
import { EventEmitter } from 'events';

export { MpvIpcClient, MpvProcessManager };
export type { MpvOptions };

export interface PlayerState {
  isPlaying: boolean;
  currentTime: number;
  duration: number;
  volume: number;
  isMuted: boolean;
  isFullscreen: boolean;
}

export class PlayerCore extends EventEmitter {
  private processManager: MpvProcessManager;
  private ipc: MpvIpcClient | null = null;
  private state: PlayerState = {
    isPlaying: false,
    currentTime: 0,
    duration: 0,
    volume: 100,
    isMuted: false,
    isFullscreen: false,
  };

  constructor() {
    super();
    this.processManager = new MpvProcessManager();
    this.processManager.on('crashed', () => {
      // MPV process died (user pressed q / window closed) -
      // drop the stale IPC client so isReady() returns false
      // and the next loadFile() restarts a fresh player.
      this.ipc = null;
      this.state.isPlaying = false;
      this.emit('crashed');
    });
  }

  async start(options?: MpvOptions): Promise<void> {
    const socketPath = await this.processManager.start(options);
    this.ipc = new MpvIpcClient(socketPath);
    await this.ipc.connect();

    // Observe key properties
    this.ipc.observeProperty('time-pos');
    this.ipc.observeProperty('duration');
    this.ipc.observeProperty('pause');
    this.ipc.observeProperty('volume');
    this.ipc.observeProperty('mute');
    this.ipc.observeProperty('fullscreen');
    this.ipc.observeProperty('eof-reached');

    this.ipc.on('property-change:time-pos', (data) => {
      this.state.currentTime = typeof data === 'number' ? data : 0;
      this.emit('time-pos', this.state.currentTime);
    });

    this.ipc.on('property-change:duration', (data) => {
      this.state.duration = typeof data === 'number' ? data : 0;
      this.emit('duration', this.state.duration);
    });

    this.ipc.on('property-change:pause', (data) => {
      this.state.isPlaying = data !== true;
      this.emit('pause', data);
    });

    this.ipc.on('property-change:volume', (data) => {
      this.state.volume = typeof data === 'number' ? data : 100;
      this.emit('volume', this.state.volume);
    });

    this.ipc.on('property-change:mute', (data) => {
      this.state.isMuted = data === true;
      this.emit('mute', this.state.isMuted);
    });

    this.ipc.on('property-change:fullscreen', (data) => {
      this.state.isFullscreen = data === true;
      this.emit('fullscreen', this.state.isFullscreen);
    });

    this.ipc.on('property-change:eof-reached', (data) => {
      if (data === true) {
        this.emit('eof');
      }
    });

    this.ipc.on('disconnect', () => {
      this.ipc = null;
      this.state.isPlaying = false;
      this.emit('disconnect');
    });

    this.emit('ready');
  }

  async quit(): Promise<void> {
    if (this.ipc) {
      this.ipc.disconnect();
      this.ipc = null;
    }
    await this.processManager.quit();
  }

  async loadFile(path: string, startPosition?: number, httpHeaders?: string): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    // Streaming (transcode HLS) endpoints need auth on EVERY request -
    // segment URLs generated by the server carry no api_key. Passing the
    // token via http-header-fields fixes segment 401/400 errors.
    if (httpHeaders) {
      await this.ipc.setProperty('http-header-fields', httpHeaders).catch(() => {});
    }

    const args: (string | Record<string, unknown>)[] = [path, 'replace'];
    if (startPosition !== undefined && startPosition > 0) {
      // mpv 0.29 (Debian 10) expects options as a string, e.g. "start=120"
      args.push(`start=${Math.floor(startPosition)}`);
    }
    await this.ipc.command('loadfile', ...args);
  }

  async pause(): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.setProperty('pause', true);
  }

  async resume(): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.setProperty('pause', false);
  }

  async togglePause(): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.command('cycle', 'pause');
  }

  async seek(seconds: number, type: 'relative' | 'absolute' = 'absolute'): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    const typeFlag = type === 'relative' ? 'relative' : 'absolute';
    await this.ipc.command('seek', seconds, typeFlag);
  }

  async setVolume(volume: number): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.setProperty('volume', Math.max(0, Math.min(100, volume)));
  }

  async setFullscreen(fullscreen: boolean): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.setProperty('fullscreen', fullscreen);
  }

  /**
   * Override the display aspect ratio. Accepted values: 'auto',
   * '16:9', '4:3', '2.35:1', '1:1' or a float like '1.7777'.
   */
  async setAspectRatio(ratio: string): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    try {
      // mpv <= 0.32 property name (our self-built player is 0.32)
      await this.ipc.setProperty('video-aspect', ratio);
    } catch {
      // mpv >= 0.33 renamed the property
      await this.ipc.setProperty('video-aspect-override', ratio);
    }
  }

  /** Show an OSD message on the video (no-op when no media loaded). */
  async showText(text: string, durationMs = 1500): Promise<void> {
    if (!this.ipc) return;
    await this.ipc.command('show-text', text, durationMs).catch(() => {});
  }

  /** Cycle to the next audio track. */
  async cycleAudio(): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.command('cycle', 'audio', 'up');
  }

  /** Cycle to the next subtitle track ('no' included). */
  async cycleSub(): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.command('cycle', 'sub', 'up');
  }

  /** Select a specific track by id. type: aid/sid/vid; id 0 = off (for subs). */
  async setTrack(type: 'aid' | 'sid' | 'vid', id: number): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.setProperty(type, id);
  }

  /** Raw track-list property (audio/sub/video tracks with selection state). */
  async getTracks(): Promise<unknown[]> {
    if (!this.ipc) return [];
    const result = (await this.ipc.command('get_property', 'track-list')) as {
      data?: unknown[];
    };
    return result?.data || [];
  }

  /** Toggle always-on-top (used for the mini/PiP window). */
  async setOntop(ontop: boolean): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.setProperty('ontop', ontop);
  }

  /** Maximize / restore the mpv window (mpv >= 0.31). */
  async setMaximized(max: boolean): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.setProperty('window-maximized', max);
  }

  /** Window scale relative to video size; < 1 shrinks (mini window). */
  async setWindowScale(scale: number): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.setProperty('window-scale', scale);
  }

  async cycleSubtitle(): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.command('cycle', 'sub');
  }

  async addSubtitle(path: string): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.command('sub-add', path);
  }

  async setSubtitleDelay(delaySeconds: number): Promise<void> {
    if (!this.ipc) throw new Error('Player not started');
    await this.ipc.setProperty('sub-delay', delaySeconds);
  }

  getState(): PlayerState {
    return { ...this.state };
  }

  isReady(): boolean {
    return this.ipc !== null && this.ipc.isConnected();
  }
}
