import { app } from 'electron';
import { join } from 'path';
import { writeFileSync, mkdirSync } from 'fs';
import { MPV_BINDINGS } from '../../../shared/shortcut-defs';

/**
 * Dynamic mpv input.conf generation.
 *
 * The bundled resources/mpv-input.conf ships sane defaults; user-editable
 * bindings are rendered from MPV_BINDINGS into a generated file under
 * userData, which mpv loads via --input-conf. Editing bindings in the UI
 * rewrites the file and hot-reloads it with set_property("input-conf").
 */

/** Non-editable entries that the generated file must always include. */
const FIXED_CONF_LINES = [
  '# Track menus (uosc pop-up menus)',
  'a script-binding uosc/audio',
  'c script-binding uosc/subtitles',
  '# Aspect ratio presets (fixed; video-aspect is the mpv <= 0.32 name)',
  'Ctrl+1 set video-aspect "auto"',
  'Ctrl+2 set video-aspect "16:9"',
  'Ctrl+3 set video-aspect "4:3"',
  'Ctrl+4 set video-aspect "2.35:1"',
  'Ctrl+5 set video-aspect "1:1"',
  'Ctrl+r cycle-values video-aspect "auto" "16:9" "4:3" "2.35:1" "1:1"',
  '# Mouse bindings (not re-recordable in-app)',
  'WHEEL_UP add volume 3',
  'WHEEL_DOWN add volume -3',
  'MBTN_LEFT_DBL cycle fullscreen',
];

/** id -> keys; missing entries fall back to defaultKeys. */
export type MpvBindingOverrides = { [id: string]: string };

export function getGeneratedConfPath(): string {
  return join(app.getPath('userData'), 'mpv-input.conf');
}

/** Return ids whose keys collide with another binding (editable set only). */
export function findMpvBindingConflicts(overrides: MpvBindingOverrides): string[] {
  const seen = new Map<string, string>();
  const conflicts: string[] = [];
  const keyOf = (id: string) => (overrides[id] || MPV_BINDINGS.find((d) => d.id === id)?.defaultKeys || '').toUpperCase();
  for (const def of MPV_BINDINGS) {
    const keys = keyOf(def.id);
    if (!keys) continue;
    const prev = seen.get(keys);
    if (prev !== undefined) {
      if (!conflicts.includes(prev)) conflicts.push(prev);
      conflicts.push(def.id);
    } else {
      seen.set(keys, def.id);
    }
  }
  return conflicts;
}

/** Render and write the generated input.conf. */
export function writeMpvInputConf(overrides: MpvBindingOverrides): void {
  const lines: string[] = [
    '# Generated by QY Player - do not edit by hand.',
    '# Customized bindings live in app_config ("mpv-shortcuts").',
    '',
  ];
  for (const def of MPV_BINDINGS) {
    const keys = overrides[def.id] || def.defaultKeys;
    lines.push(`${keys} ${def.command}`);
  }
  lines.push('', '# Fixed bindings', ...FIXED_CONF_LINES, '');
  mkdirSync(app.getPath('userData'), { recursive: true });
  writeFileSync(getGeneratedConfPath(), lines.join('\n'), 'utf-8');
}
