export const IPC_CHANNELS = {
  PLAYER: {
    LOAD_FILE: 'player:load-file',
    RESOLVE: 'player:resolve',
    CONTROL: 'player:control',
    GET_STATE: 'player:get-state',
    GET_TRACKS: 'player:get-tracks',
    PROBE_ITEM: 'player:probe-item',
    ON_STATE_CHANGE: 'player:on-state-change',
  },
  LIBRARY: {
    OPEN_FILE: 'library:open-file',
    OPEN_FOLDER: 'library:open-folder',
    GET_RECENTLY_PLAYED: 'library:get-recently-played',
    CLEAR_HISTORY: 'library:clear-history',
    DELETE_HISTORY: 'library:delete-history',
  },
  ONLINE: {
    GET_LIBRARIES: 'online:get-libraries',
    GET_ITEMS: 'online:get-items',
    GET_ITEM_DETAILS: 'online:get-item-details',
    GET_STREAM_URL: 'online:get-stream-url',
    GET_CONTINUE_WATCHING: 'online:get-continue-watching',
    SEARCH: 'online:search',
  },
  PROGRESS: {
    SAVE: 'progress:save',
    GET: 'progress:get',
    GET_CONTINUE: 'progress:get-continue',
  },
  SETTINGS: {
    GET: 'settings:get',
    SET: 'settings:set',
    GET_SERVERS: 'settings:get-servers',
    SAVE_SERVER: 'settings:save-server',
    TEST_SERVER: 'settings:test-server',
    SECRETS_PERSISTENT: 'settings:secrets-persistent',
  },
  WINDOW: {
    ENTER_PLAYER_MODE: 'window:enter-player-mode',
    EXIT_PLAYER_MODE: 'window:exit-player-mode',
    SET_FULLSCREEN: 'window:set-fullscreen',
  },
  SHORTCUTS: {
    APPLY: 'shortcuts:apply',
    APPLY_MPV: 'shortcuts:apply-mpv',
  },
  // Phase 2 unified catalog domain (handlers land in QYP2-008+; the channel
  // names are part of the QYP2-002 contract and must not be renamed).
  CATALOG: {
    PICK_DIR: 'catalog:pick-dir',
    SOURCE_LIST: 'catalog:source-list',
    SOURCE_TEST: 'catalog:source-test',
    SOURCE_SAVE: 'catalog:source-save',
    SOURCE_REMOVE: 'catalog:source-remove',
    SOURCE_HEALTH: 'catalog:source-health',
    SCAN_START: 'catalog:scan-start',
    SCAN_CANCEL: 'catalog:scan-cancel',
    SCAN_EVENTS: 'catalog:scan-events',
    LIST: 'catalog:list',
    GET: 'catalog:get',
    SEARCH: 'catalog:search',
    RESOLVE: 'catalog:resolve',
  },
  SUBTITLES: {
    PICK_FILE: 'subtitles:pick-file',
    IMPORT: 'subtitles:import',
    LIST: 'subtitles:list',
    REMOVE: 'subtitles:remove',
    SET_DEFAULT: 'subtitles:set-default',
  },
  METADATA: {
    GET: 'metadata:get',
    SAVE: 'metadata:save',
    RESTORE: 'metadata:restore',
    PICK_IMAGE: 'metadata:pick-image',
    IMPORT_IMAGES: 'metadata:import-images',
  },
  MEDIA: {
    DELETE_PREVIEW: 'media:delete-preview',
    DELETE_EXECUTE: 'media:delete-execute',
  },
  PLUGINS: {
    LIST: 'plugins:list',
    SET_CONFIG: 'plugins:set-config',
    SET_SECRET: 'plugins:set-secret',
    DELETE_SECRET: 'plugins:delete-secret',
    TEST: 'plugins:test',
  },
} as const;
